# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: KInfo
site_description: KInfo library documentation
site_url: https://io.github.n7ghtm4r3/KInfo/

repo_name: KInfo
repo_url: https://github.com/N7ghtm4r3/KInfo
site_author: Manuel Maurizio

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: lime
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  language: en

  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Overview: index.md
  - Usage: usage.md
  - Android:
      - Overview: android/index.md
      - App info: android/app_info.md
      - OS info: android/os_info.md
      - Device info: android/device_info.md
      - ABIs: android/abis.md
      - Tags: android/tags.md
      - System features: android/system_features.md
      - Display: android/display.md
      - Locale: android/locale.md
  - iOS:
      - Overview: ios/index.md
      - App info: ios/app_info.md
      - Device info: ios/device_info.md
      - Locale: ios/locale.md
  - Desktop: desktop/index.md
  - Web:
      - Overview: web/index.md
      - Browser info: web/browser_info.md
      - Device info: web/device_info.md

extra:
  social:
    - icon: material/email
      link: mailto:infotecknobitcompany@gmail.com
    - icon: material/bug
      link: https://github.com/swapnil-musale/KDeviceInfo/issues

copyright: |
  &copy; 2025 <a href="https://github.com/N7ghtm4r3" target="new">N7ghtm4r3 - Tecknobit</a>