[versions]
agp = "9.3.1"
kotlin = "2.4.10"
mavenPublish = "0.37.0"
android-minSdk = "24"
android-compileSdk = "37"
composeMultiplatform = "1.11.1"
dokka = "2.2.0"
annotation = "1.10.0"
oshi = "7.5.0"
startupRuntime = "1.2.0"
androidXCore = "1.19.0"
equinox = "1.2.0"
kotlin-browser = "0.5.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
equinox-compose = { module = "io.github.n7ghtm4r3:equinox-compose", version.ref = "equinox" }
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }

[plugins]


composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }